# -*- coding: utf-8 -*-
"""Divide and conquer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A22fAvEenvBa2bmqx17zBVwsmB2RQmuj

# Assignment 3 - Divide-n-Conquer Algorithms in Python

_This assignment is a part of the course ["Data Structures and Algorithms in Python"](https://jovian.ai/learn/data-structures-and-algorithms-in-python)._

In this assignment, you will implement an efficient algorithm for polynomial multiplication.

As you go through this notebook, you will find the symbol **???** in certain places. To complete this assignment, you must replace all the **???** with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end. 

**Guidelines**

1. Make sure to run all the code cells, otherwise you may get errors like `NameError` for undefined variables.
2. Do not change variable names, delete cells or disturb other existing code. It may cause problems during evaluation.
3. In some cases, you may need to add some code cells or new statements before or after the line of code containing the **???**. 
4. Since you'll be using a temporary online service for code execution, save your work by running `jovian.commit` at regular intervals.
5. Questions marked **(Optional)** will not be considered for evaluation, and can be skipped. They are for your learning.
6. If you are stuck, you can ask for help on the [community forum] (TODO - add link). Post errors or ask for hints, but **please don't ask for OR share the full working answer code** on the forum.
7. There are some tests included with this notebook to help you test your implementation. However, after submission your code will be tested with some hidden test cases. Make sure to test your code exhaustively to cover all edge cases.


**Important Links**

* Submit your work here: https://jovian.ai/learn/data-structures-and-algorithms-in-python/assignment/assignment-3-sorting-and-divide-conquer-practice
* Ask questions and get help: https://jovian.ai/forum/c/data-structures-and-algorithms-in-python/assignment-3/89
* Lesson 3 video for review: https://jovian.ai/learn/data-structures-and-algorithms-in-python/lesson/lesson-3-sorting-algorithms-and-divide-and-conquer
* Lesson 3 notebook for review: https://jovian.ai/aakashns/python-sorting-divide-and-conquer

### How to Run the Code and Save Your Work

**Option 1: Running using free online resources (1-click, recommended)**: Click the **Run** button at the top of this page and select **Run on Binder**. You can also select "Run on Colab" or "Run on Kaggle", but you'll need to create an account on [Google Colab](https://colab.research.google.com) or [Kaggle](https://kaggle.com) to use these platforms.


**Option 2: Running on your computer locally**: To run the code on your computer locally, you'll need to set up [Python](https://www.python.org) & [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/), download the notebook and install the required libraries. Click the **Run** button at the top of this page, select the **Run Locally** option, and follow the instructions.

**Saving your work**: You can save a snapshot of the assignment to your [Jovian](https://jovian.ai) profile, so that you can access it later and continue your work. Keep saving your work by running `jovian.commit` from time to time.
"""

project='python-divide-and-conquer-assignment'

!pip install jovian --upgrade --quiet

import jovian
jovian.commit(project=project, privacy='secret', environment=None)

"""## Problem Statement - Polynomial Multiplication

> Given two polynomials represented by two lists, write a function that efficiently multiplies given two polynomials. For example, the lists `[2, 0, 5, 7]` and `[3, 4, 2]` represent the polynomials $2 + 5x^2 + 7x^3$ and $3 + 4x + 2x^2$. 
> 
> Their product is 
>
> $(2 \times 3) + (2 \times 4 + 0 \times 3)x + (2 \times 2 + 3 \times 5 + 4 \times 0)x^2 + (7 \times 3 + 5 \times 4 + 0 \times 2)x^3 + (7 \times 4 + 5 \times 2)x^4 + (7 \times 2)x^5$ i.e. 
>
>$6 + 8x + 19x^2 + 41x^3 + 38x^4 + 14x^5$
> 
>It can be represented by the list `[6, 8, 19, 41, 38, 14]`.

## The Method

Here's the systematic strategy we'll apply for solving problems:

1. State the problem clearly. Identify the input & output formats.
2. Come up with some example inputs & outputs. Try to cover all edge cases.
3. Come up with a correct solution for the problem. State it in plain English.
4. Implement the solution and test it using example inputs. Fix bugs, if any.
5. Analyze the algorithm's complexity and identify inefficiencies, if any.
6. Apply the right technique to overcome the inefficiency. Repeat steps 3 to 6.

This approach is explained in detail in [Lesson 1](https://jovian.ai/learn/data-structures-and-algorithms-in-python/lesson/lesson-1-binary-search-linked-lists-and-complexity) of the course. Let's apply this approach step-by-step.

## Solution


### 1. State the problem clearly. Identify the input & output formats.

While this problem is stated clearly enough, it's always useful to try and express in your own words, in a way that makes it most clear for you. 


**Problem**

> a function that will multiply 2 given polynomials.

<br/>


**Input**

1. `[2, 4, 0, 0, 5]` and `[4, 9, 5, 4]`
2. `[2, 4]` and `[2, 7, 5]`
 



**Output**

1. `[8 34 46 28 36 45 25 20]`
2. `[4 22 38 20]`


<br/>

Based on the above, we can now create a signature of our function:
"""

def multiply(poly1, poly2):
    pass

import jovian

jovian.commit()

"""### 2. Come up with some example inputs & outputs. Try to cover all edge cases.

Our function should be able to handle any set of valid inputs we pass into it. List a few scenarios here:

1. One list is empty (result would be 0s)
2. One list is of 1s (result would be Other List).
3. Both lists are same.
4. Both lists are of same/different size (a really long list.).
5. A list containing just one element. (add more if required)

(add more if required)


Create a test case of each of the above scenarios. We'll express our test cases as dictionaries, to test them easily. Each dictionary will contain 2 keys: `input` (a dictionary itself containing one key for each argument to the function and `output` (the expected result from the function). 
"""

test0 = {
    'input': {
        'poly1': [2, 0, 5, 7],
        'poly2': [3, 4, 2]
    },
    'output': [6, 8, 19, 41, 38, 14]
}

test1 = {
    'input': {
        'poly1': [2, 4, 0, 0, 5],
        'poly2': [4, 9, 5, 4]
    },
    'output': [8, 34, 46, 28, 36, 45, 25, 20]
}

test2 = {
    'input': {
        'poly1': [2, 4],
        'poly2': [2, 7, 5]
    },
    'output': [4, 22, 38, 20]
}

test3 = {
    'input': {
        'poly1': [1, 1, 1],
        'poly2': [2, 7, 5]
    },
    'output': [2, 9, 14, 12, 5]
}

test4 = {
    'input': {
        'poly1': [],
        'poly2': [2, 7, 4]
    },
    'output': []
}

test5 = {
    'input': {
        'poly1': [0, 1],
        'poly2': [2, 6, -5, 3, 4]
    },
    'output': [0, 2, 6, -5, 3, 4]
}

test6 = {
    'input': {
        'poly1': [1],
        'poly2': [2, 6, 5, 3, 4]
    },
    'output': [2, 6, 5, 3, 4]
}

test7 = {
    'input': {
        'poly1': [],
        'poly2': [1]
    },
    'output': []
}

test8 = {
    'input': {
        'poly1': [2, 5, 3, 1, -1],
        'poly2': [1, 2, 2, 3, 6]
    },
    'output': [2, 9, 17, 23, 34, 39, 19, 3, -6]
}

# add more if required

"""Let's store all the test cases in a list, for easier automated testing."""

tests = [test0, test1, test2, test3, test4, test5, test6, test7, test8]

import jovian

jovian.commit()

"""### 3. Come up with a correct solution for the problem. State it in plain English.

Our first goal should always be to come up with a _correct_ solution to the problem, which may not necessarily be the most _efficient_ solution. 

Here's the simplest solution: If you have lists `poly1` and `poly2` representing polynomials of length $m$ and $n$ respectively, the highest degree of the exponents are $m-1$ and $n-1$ respectively. Their product has the degree $(m - 1) + (n - 1)$ i.e $m + n - 2$. The list representing the product has the length $m + n - 1$. So, we can create a list `result` of length $m + n - 1$, and set 

`result[k]` = Sum of all the pairs `poly1[i] * poly2[j]` where `i+j = k`

Example:

$(2 + 5x^2 + 7x^3) \times (3 + 4x + 2x^2)$

$= (2 \times 3) + (2 \times 4 + 0 \times 3)x + (2 \times 2 + 3 \times 5 + 4 \times 0)x^2 + (7 \times 3 + 5 \times 4 + 0 \times 2)x^3 + (7 \times 4 + 5 \times 2)x^4 + (7 \times 2)x^5$

$= 6 + 8x + 19x^2 + 41x^3 + 38x^4 + 14x^5$






Explain this solution in your own words below:

1. Create an emply list (result) with len(poly1) + len(poly2) - 1.
2. Set the first element result[0] to poly1[0]*poly2[0] as this would be the value with multiplier 
3. Second element result[1] would be poly1[1]*poly2[0] + poly1[0]*poly2[1], as these would have multiplier.
4. Effectively, index could be read as the degree of the exponents and the value at the index as multiplier.
5. i.e. result[k] = Sum of all the pairs poly1[i] * poly2[j] where i+j = k (add more steps if required)

(add more steps if required)


Let's save and upload our work before continuing.


"""

import jovian

jovian.commit()

"""###  4. Implement the solution and test it using example inputs. Fix bugs, if any.

Implement the solution
"""

def multiply_basic(poly1, poly2):
    m = len(poly1)
    n = len(poly2)
    
    if m>0 and n>0:
      result = [0]*(m + n - 1) 
      for i in range(m):
        for j in range(n):
          result[i+j] += poly1[i] * poly2[j]           
    
    elif m==0 or n==0:
        result = [] 
    
    elif n==0:
        result = []
    
    return result

"""Test your solution using the test cases you've defined above."""

print('Input-1:', test1['input']['poly1'])
print('Input-2:', test1['input']['poly2'])
print('Expected output:', test1['output'])
result1 = multiply_basic(test1['input']['poly1'], test1['input']['poly2'])
print('Actual output:', result1)
print('Match:', result1 == test1['output'])

from jovian.pythondsa import evaluate_test_cases

results = evaluate_test_cases(multiply_basic, tests)





import jovian

jovian.commit()

"""### 5. Analyze the algorithm's complexity and identify inefficiencies, if any.

Can you analyze the time and space complexity of this algorithm?
"""

multiply_basic_time_complexity = 'O(n^2)' # Time complexity is m+n-1, as we are calculating items for each result index

multiply_basic_space_complexity = 'O(N*N)' 
# For calculating the result[i], we are storing all multiplication results, til we find i+j=k. Hence sm*n!



import jovian

jovian.commit()

"""### 6. Apply the right technique to overcome the inefficiency. Repeat steps 3 to 6.

We can apply the divide and conquer technique to solve this problem more efficiently. Given two polynomials `A` and `B`, we can express each of them as a sum of two polynomials as follows:

<img src="https://i.imgur.com/FjKQF5h.png" width="480">

We need to compute the terms `A0 * B0`, `A1 * B0 + A0 * B1` and `A1 * B1`. This can obviously be done using 4 multiplications, but here's a way of doing it with just three multiplications:

<img src="https://i.imgur.com/G3vD1GX.png" width="480">


Each of the products can themselves be computed recursively. For a more detailed explanation of this approach see http://www.cse.ust.hk/~dekai/271/notes/L03/L03.pdf .


Need help? Discuss and ask questions on the forum: https://jovian.ai/forum/c/data-structures-and-algorithms-in-python/assignment-3/89

### 7. Come up with a correct solution for the problem. State it in plain English.

Explain the approach described above in your own words below:

1. Divide the polynomials A & B in smaller polynomials Such as  𝐴(𝑥)  as  𝐴0(𝑥)  and  𝐴1(𝑥) (say half)
2. The original problem of size n is divided into 4 problems of input size n/2.
3. Solve the four subproblems, by recursively calling the algorithm 4 times.

(add more steps if required)


Let's save and upload our work before continuing.
"""

import jovian

jovian.commit()

"""### 8. Implement the solution and test it using example inputs. Fix bugs, if any.

We are now ready to implement the solution. You may find the following functions `add`, `split` and `increase_exponent` useful.

"""

def add(poly1, poly2):
    """Add two polynomials"""
    result = [0] * max(len(poly1), len(poly2))
    for i in range(len(result)):
        if i < len(poly1):
            result[i] += poly1[i]
        if i < len(poly2):
            result[i] += poly2[i]
    return result

add([1, 2, 3, 4], [0, 4, 3])

def split(poly1, poly2):
    """Split each polynomial into two smaller polynomials"""
    mid = max(len(poly1), len(poly2)) // 2
    return  (poly1[:mid], poly1[mid:]), (poly2[:mid], poly2[mid:])

split([1, 2, 3, 4], [0, 4, 3, 6, 7, 8, 2])

def increase_exponent(poly, n):
    """Multiply poly1 by x^n"""
    return [0] * n + poly

increase_exponent([1, 2, 3, 4], 3)

"""Implement the optimized multiplication algorithm below. You may use the some or all of the helper functions defined above."""

# What this does is takes the first element of poly1, multiplies all elements of poly2


# Standardizes the polynomial (Gets rid of trailing 0s)
def standardize(poly):
    poly = list(poly) # make a copy
    if poly[len(poly)-1] == 0: # Check if the last element in the list is 0
        poly.pop() #If last element is zero, remove from the list
    return poly

# Finds if the polynomial is 0
def isZeroPoly(poly):
    if poly == []: # Check if poly is blank [] or [0]<= standardize would remove the zero and return []
        return True
    else:
        return False

# Scales the polynomial by the scale variable ((3,[1,2,3]) => [3,6,9])
def scalePoly(scale,poly):
    poly = list(poly)
    for x in range(0,len(poly)): # For final assembly of resulting poly
        poly[x] = (poly[x] * scale)
    poly = standardize(poly)
    return poly

# Gives the constant in the polynomial ([2,3,4] => [2])
def constCoef(poly):
    constant = poly[0]
    return constant

# Shifts the polynomial left ([2,3,4] => [0,2,3,4])
def shiftLeft(poly):
    newpoly = []
    newpoly.append(0)
    for x in range(0,len(poly)): # Increase exponent
        newpoly.append(poly[x])
    return newpoly

# Shifts the polynomial right ([2,3,4] => [3,4])
def shiftRight(poly):
    #poly.remove(poly[0])
    return poly[1:]

def multiply_optimized(poly1, poly2):
    # print (poly1, poly2)
    if isZeroPoly(poly1):
        return []
    else:
        return add(
            multiply_optimized(shiftRight(poly1), shiftLeft(poly2)),
            scalePoly(constCoef(poly1), poly2)
        )

multiply_optimized([1, 2, 3, 4], [0, 4, 3, 6, 7, 8, 2])



results = evaluate_test_cases(multiply_optimized, tests)







import jovian

jovian.commit()

"""## Make a Submission

Congrats! You have now implemented hash tables from scratch. The rest of this assignment is optional.

You can make a submission on this page: https://jovian.ai/learn/data-structures-and-algorithms-in-python/assignment/assignment-3-sorting-and-divide-conquer-practice

Submit the link to your Jovian notebook (the output of the previous cell).
You can also make a direct submission by executing the following cell:
"""

jovian.submit(assignment="pythondsa-assignment3")

"""### (Optional) 9. Analyze the algorithm's complexity and identify inefficiencies, if any.

Can you analyze the time and space complexity of this algorithm? 

Hint: See the tree of subproblems below ([source](https://myithelpcentral.blogspot.com/2015/09/o-logn-notation-explanation-for-binary.html)). Substitute the right values for `n` and `b` to determine the time complexity.

![](https://i.imgur.com/JAmZrE5.png)
"""

import jovian

jovian.commit()